#!/usr/bin/env python3
"""
Build the public sample data for `data_sample/`.

Slices the four full output CSVs to a single year and writes them to a
small directory that is safe to commit. Default year is the most recent
COMPLETE calendar year present in the data.

USAGE
-----
  python scripts/02_build_sample.py --output-dir outputs --sample-dir data_sample
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Optional

import pandas as pd


SUFFIXES = {
    "raw": "_raw.csv",
    "county_panel": "_county_panel.csv",
    "event_level": "_event_level.csv",
    "year_stats": "_year_stats.csv",
}


def find_input_files(output_dir: Path) -> dict[str, Path]:
    found: dict[str, Path] = {}
    for kind, suffix in SUFFIXES.items():
        matches = sorted(output_dir.glob(f"*{suffix}"))
        if matches:
            found[kind] = max(matches, key=lambda p: p.stat().st_mtime)
    return found


def pick_sample_year(year_stats_path: Path) -> int:
    df = pd.read_csv(year_stats_path)
    current_year = datetime.now().year
    complete_years = sorted(y for y in df["year"].astype(int) if y < current_year)
    if not complete_years:
        return int(df["year"].astype(int).max())
    return complete_years[-1]


def slice_to_year(df: pd.DataFrame, year: int) -> pd.DataFrame:
    for col in ("year", "YEAR"):
        if col in df.columns:
            return df[df[col].astype(int) == year].copy()
    return df


def build_sample(
    output_dir: Path, sample_dir: Path, sample_year: Optional[int] = None
) -> List[Path]:
    files = find_input_files(output_dir)
    if "year_stats" not in files:
        print(f"No year_stats CSV in {output_dir}; cannot pick a sample year.")
        return []

    year = sample_year or pick_sample_year(files["year_stats"])
    print(f"Using sample year: {year}")

    sample_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []

    for kind, path in files.items():
        print(f"  Reading {path.name}...")
        df = pd.read_csv(path, low_memory=False)
        sliced = slice_to_year(df, year)
        out_path = sample_dir / f"sample_{year}_{kind}.csv"
        sliced.to_csv(out_path, index=False)
        size_kb = out_path.stat().st_size / 1024
        print(f"    -> {out_path.name} ({len(sliced):,} rows, {size_kb:.0f} KB)")
        written.append(out_path)

    readme = sample_dir / "README.md"
    readme.write_text(
        f"""# NOAA Storm Events — Sample Data

This folder holds a single-year slice ({year}) of the four pipeline outputs.
The complete dataset (1984-present) lives in S3 and/or OSF; see the repo
README for access.

| File | Description |
|------|-------------|
| `sample_{year}_raw.csv` | Raw NOAA Storm Events records as downloaded. |
| `sample_{year}_county_panel.csv` | One row per county for {year}, with event-type counts and casualty totals. |
| `sample_{year}_event_level.csv` | Every event with `county_fips` and `county_name` joined on. |
| `sample_{year}_year_stats.csv` | Single-row summary for {year}. |

Auto-generated by `scripts/02_build_sample.py` on {datetime.now().strftime('%Y-%m-%d')}.
"""
    )
    written.append(readme)
    return written


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build sample data for the public repo.")
    p.add_argument("--output-dir", type=Path, default=Path("outputs"))
    p.add_argument("--sample-dir", type=Path, default=Path("data_sample"))
    p.add_argument("--year", type=int)
    return p.parse_args()


def main() -> int:
    args = parse_args()
    if not args.output_dir.exists():
        print(f"{args.output_dir} does not exist.", file=sys.stderr)
        return 1
    written = build_sample(args.output_dir, args.sample_dir, args.year)
    print(f"\nWrote {len(written)} file(s) to {args.sample_dir}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
